name: CI

on: push
jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest

      - name: Run Biome
        run: biome ci . # https://biomejs.dev/reference/cli/#biome-ci