name: Pull Request

on: pull_request

jobs:
  quality:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Biome
          uses: biomejs/setup-biome@v1
          with:
            version: latest

        - name: Run Biome
          run: biome ci . # https://biomejs.dev/reference/cli/#biome-ci
  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build

on: pull_request
  branches:
      - 'master'

jobs:
  quality:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Biome
          uses: biomejs/setup-biome@v1
          with:
            version: latest

        - name: Run Biome
          run: biome ci . # https://biomejs.dev/reference/cli/#biome-ci
  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build

      - name: Check if version has been updated
        id: check-version-changed
        uses: EndBug/version-check@v2
        with:
          diff-search: true

      - name: Log when changed
        if: steps.check-version-changed.outputs.changed == 'true'
        run: |
          echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"

      - name: Log when unchanged
        if: steps.check-version-changed.outputs.changed == 'false'
        run: |
          echo "No version change. Please update the package version in package.json"
          exit 1