name: 'Pull Request'

on: pull_request

jobs:
  quality:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Biome
          uses: biomejs/setup-biome@v1
          with:
            version: latest

        - name: Run Biome
          run: biome ci . # https://biomejs.dev/reference/cli/#biome-ci
  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build